function appended_data = append_behavior_data(data2append)
% appended_data = append_behavior_data(data2append)
% This function is similar to append_behavioral_data used to compute
% behavioral performance (in Scripts/Behavior_ICM). 
% INPUT: 
%       - data2append:      1xN cell array of stimulation matrix and
%                           behavioral responses generated by the function Combine_BehavioralMat
% OUTPUT:
%       - appended_data:    structure with the fields from stimulation
%                           matrix & Resp, RT, Perf and Correct. 
% DA 2017/04/19 

% Initialize design variable 
Pairs = []; 
DeltaQ = []; 
SigmaQ = []; 
RawRatings = []; 
ActualMeanColors = []; 
StartingMeanColors = []; 
TitlesLength = []; 
Task = []; 
ScreenPosition = []; 
ColorVector = []; 
Block = []; 
StimWidth = []; 

% Initialize response variables 
Resp =[];
RT = [];
Perf= [];
Correct= [];

% Subject and the movie she has seen do not change
SUB = data2append{1}.Subject;
seen_movies = data2append{1}.TitlesStr; 

for iR = 1:length(data2append)
    
    Pairs = [Pairs; data2append{iR}.Pairs];
    DeltaQ = [DeltaQ; data2append{iR}.DeltaQ];
    SigmaQ = [SigmaQ; data2append{iR}.SigmaQ];
    RawRatings = [RawRatings; data2append{iR}.RawRatings];
    ActualMeanColors = [ActualMeanColors; data2append{iR}.ActualMeanColors];
    StartingMeanColors = [StartingMeanColors; data2append{iR}.StartingMeanColors];
    TitlesLength = [TitlesLength; data2append{iR}.TitlesLength];
    Task = [Task; data2append{iR}.Task];
    ScreenPosition = [ScreenPosition; data2append{iR}.ScreenPosition];
    ColorVector = [ColorVector; data2append{iR}.ColorVector];
    Block = [Block; data2append{iR}.Block];
    StimWidth = [StimWidth; data2append{iR}.StimWidth];
    
    % Subject responses
    Resp =[Resp; data2append{iR}.Resp];
    RT = [RT; data2append{iR}.RT];
    Perf= [Perf; data2append{iR}.Perf];
    Correct= [Correct; data2append{iR}.CorrectResp];
    
end

% OUTPUT
appended_data                     = [];
appended_data.Subject             = SUB;
appended_data.SeenMovies          = seen_movies;
appended_data.Pairs               = Pairs;
appended_data.DeltaQ              = DeltaQ;
appended_data.SigmaQ              = SigmaQ;
appended_data.RawRatings          = RawRatings;
appended_data.ActualMeanColors    = ActualMeanColors;
appended_data.StartingMeanColors  = StartingMeanColors;
appended_data.TitlesLength        = TitlesLength;
appended_data.Task                = Task;
appended_data.ScreenPosition      = ScreenPosition;
appended_data.ColorVector         = ColorVector;
appended_data.Block               = Block;
appended_data.StimWidth           = StimWidth;
appended_data.Response            = Resp;
appended_data.RT                  = RT;
appended_data.Performance         = Perf;
appended_data.CorrectResp         = Correct;


end