% S04_GLM1ab_ProjectDefautAnatomy.m
%
% The script project the whole time-serie of source reconstructed signal
% onto the default anatomy.
%
% Script generated by Brainstorm (20-Feb-2018)
% DA 2018/03/03: Modified for batching
% DA 2018/03/10: adapted for projecting smoothed files (with different level of smoothing)
%                or non-smoothed files.
% DA 2018/03/29: Adapted from SR6_ProjectDefautAnatomy.m for data in
%                GLM_Hunt on sources. 
% DA 2019/07/24: Name has been changed to comply with GLM name in the main text (originally
%                S04_GLM_Hunt_2013_ProjectDefaultAnatomy.m). 
%                Note that the same code is used to project all the beta estimated at the 
%                source level, therefore, the names of the folder (Tasks) should be adapted. 
%                

clc
clear

ss                  = [11:13 15:17 19:30 32:34];
Tasks               = {'BetaChosenVal_avgTime_-0.580to-0.197'};
source_path         =  '/Volumes/PREFER/Brainstorm_db/PREFER/data';

%%%%%%%%%% ============ PROJECT SMOOTHED OR NOT =============== %%%%%%%%%%
project_smoothed    = false;
smoothing_fn        = 'ssmooth_02'; % The filename corresponding to the applied smoothing
%%%%%%%%%% ===================================================== %%%%%%%%%%
% addpath('/Users/etudiant/Documents/PREFER/brainstorm3/');
% brainstorm

% How many files per each subject 
sFiles              = cell(1,length(ss)*1);
n                   = 0;

if project_smoothed == false
    fprintf('\n');
    warning(' YOU SELECTED TO PROJECT NON-SMOOTHED FILES');
elseif project_smoothed == true
    fprintf('\n');
    warning(' YOU SELECTED TO PROJECT SMOOTHED FILES; \n SMOOTHING FN = %s',smoothing_fn);
end

for iS    = ss
    for iTask = 1:length(Tasks)
        % Search for filename wiht ssmooth at the end (BEWARE IF THERE ARE MANY)
        fn          = [];
        fn          = dir(fullfile(source_path,sprintf('S%02d/%s',iS,Tasks{iTask}),strcat('results*.mat')));
        
        for iF = 1:length(fn)
            
            % PROJECT NON-SMOOTHED FILES
            if project_smoothed == false
                if isempty(strfind(fn(iF).name,'smooth'))
                    n=n+1;
                    sFiles{1,n} = fullfile(sprintf('S%02d/%s',iS,Tasks{iTask}),fn(iF).name);
                end
            % PROJECT SMOOTHED FIELS
            elseif project_smoothed == true
                if ~isempty(strfind(fn(iF).name,sprintf('%s',smoothing_fn)))
                    n=n+1;
                    sFiles{1,n} = fullfile(sprintf('S%02d/%s',iS,Tasks{iTask}),fn(iF).name);
                end
            end
        end
    end
end

% Start a new report
bst_report('Start', sFiles);

% Process: Project on default anatomy: surface
sFiles = bst_process('CallProcess', 'process_project_sources', sFiles, [], ...
    'headmodeltype', 'surface');  % Cortex surface

% Save and display report
ReportFile = bst_report('Save', sFiles);
bst_report('Open', ReportFile);
% bst_report('Export', ReportFile, ExportDir);

